### ISSUE TITLE
问下如何用来查看日志

### ISSUE THREAD

**Issue by yangxuan8282** [leeshd/log2web#1]
我尝试用下面的命令查看本机的 log

```
tail -f /var/log/syslog 2>&1 | ./log2web -h=0.0.0.0 -p=6699 -w=ws://0.0.0.0:6699/logws
```

不过访问 http://127.0.0.1:6699/log 没显示日志内容

**Comment by leeshd** [comment]
感谢试用！

1. 先把代码clone下来，进入代码目录启动命令，主程序依赖 html和js文件

2.  -w参数  ws://{主机的ip}:6699/logws

3.  启动程序后，打开网页 

4.  在命令行中产生syslog日志
logger  "test syslog  to web"
![image](https://user-images.githubusercontent.com/3280471/57759738-2afd7c80-772d-11e9-81b8-2f6e7ab5856f.png)
![image](https://user-images.githubusercontent.com/3280471/57759848-4a94a500-772d-11e9-84c2-49aed91aaee0.png)
![image](https://user-images.githubusercontent.com/3280471/57759974-5f713880-772d-11e9-9890-b22faa3d856a.png)



> 我尝试用下面的命令查看本机的 log
> 
> ```
> tail -f /var/log/syslog 2>&1 | ./log2web -h=0.0.0.0 -p=6699 -w=ws://0.0.0.0:6699/logws
> ```
> 
> 不过访问 http://127.0.0.1:6699/log 没显示日志内容

**Comment by yangxuan8282** [comment]
可以显示日志了，可能因为websocket 那得写本机 ip 才行，就是延迟好像比较大，可能我机器网络的原因


![image](https://user-images.githubusercontent.com/6976464/57768019-46708380-773d-11e9-9777-df18e29928e3.png)
